apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: flex-trello-docs
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://flex-docs.intern.dev.nav.no
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
    sidecar:
      enabled: true
      autoLogin: false
  resources:
    limits:
      memory: 250Mi
    requests:
      cpu: 100m
      memory: 250Mi
  liveness:
    path: api/internal/isAlive
  readiness:
    path: api/internal/isAlive
  startup:
    path: api/internal/isAlive
    initialDelay: 10
  accessPolicy:
    outbound:
      external:
        - host: api.trello.com
        - host: trello.com
  envFrom:
    - secret: flex-trello-docs-trello-secrets
  env:
    - name: TRELLO_OKR_BOARD
      value: 0gO6UCsS
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
