import { InnteksOpplysningSoknad } from '@/bigquery/inntektsopplysninger/IoType'

export const ioTestdata: InnteksOpplysningSoknad[] = [
    {
        sendt: {
            value: '2024-01-29T11:56:06.623249000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-26T10:24:19.808742000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-27T05:33:11.154120000Z',
        },
        drift_virksomheten_ja: null,
        drift_virksomheten_nei: 'CHECKED',
        drift_virksomheten_opphort_dato: '2023-09-13',
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-26T10:15:15.732196000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-27T11:37:11.242214000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-27T09:51:28.426713000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:26:34.748021000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:38:57.482921000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:43:14.283221000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T10:58:24.487391000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-26T08:34:06.185266000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T10:02:19.112011000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: 'CHECKED',
        ny_i_arbeidslivet_dato: '2022-01-25',
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T13:21:19.075161000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:11:23.944040000Z',
        },
        drift_virksomheten_ja: null,
        drift_virksomheten_nei: 'CHECKED',
        drift_virksomheten_opphort_dato: '2023-12-23',
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T11:29:58.093850000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: 'CHECKED',
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: 'JA',
    },
    {
        sendt: {
            value: '2024-01-29T08:14:30.497307000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T13:34:23.559264000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-28T17:05:29.647102000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:58:03.373164000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-26T13:26:22.621084000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T14:24:18.770183000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:04:15.321247000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: 'CHECKED',
        ny_i_arbeidslivet_dato: '2020-02-10',
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:22:36.180915000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-26T15:04:50.386907000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T11:17:36.919442000Z',
        },
        drift_virksomheten_ja: null,
        drift_virksomheten_nei: 'CHECKED',
        drift_virksomheten_opphort_dato: '2024-01-16',
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-26T08:35:28.206498000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: 'CHECKED',
        varig_endring_endret_innsats: 'CHECKED',
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: 'CHECKED',
        varig_endring_annet: null,
        varig_endring_25_prosent: 'NEI',
    },
    {
        sendt: {
            value: '2024-01-29T12:28:42.395279000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T11:27:43.595828000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T11:08:44.518308000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:22:20.791733000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:54:23.031077000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T10:34:00.398559000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T10:04:21.926863000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:04:15.044797000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:43:36.145859000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: 'CHECKED',
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: 'NEI',
    },
    {
        sendt: {
            value: '2024-01-28T14:15:47.359757000Z',
        },
        drift_virksomheten_ja: null,
        drift_virksomheten_nei: 'CHECKED',
        drift_virksomheten_opphort_dato: '2023-10-12',
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:22:32.729493000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-26T11:08:03.019746000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T06:28:25.348350000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T09:28:31.410668000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-28T11:07:02.252584000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T13:00:01.574944000Z',
        },
        drift_virksomheten_ja: null,
        drift_virksomheten_nei: 'CHECKED',
        drift_virksomheten_opphort_dato: '2022-09-22',
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-26T11:56:31.795446000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T09:36:03.667968000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T09:04:45.555494000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-26T16:26:07.632729000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T09:59:22.774831000Z',
        },
        drift_virksomheten_ja: null,
        drift_virksomheten_nei: 'CHECKED',
        drift_virksomheten_opphort_dato: '2023-11-08',
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:06:30.167898000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:50:56.443014000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T09:45:23.536825000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T09:20:06.899157000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-28T09:35:19.065680000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-25T23:16:10.453430000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-27T11:29:57.315883000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T08:47:16.410836000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T10:50:01.426830000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T13:38:58.355063000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:44:38.686420000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T08:13:15.317865000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:34:23.419402000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: 'CHECKED',
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: 'JA',
    },
    {
        sendt: {
            value: '2024-01-27T11:57:10.626417000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: 'CHECKED',
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: 'JA',
    },
    {
        sendt: {
            value: '2024-01-29T12:49:06.142962000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T13:47:30.449633000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: 'CHECKED',
        varig_endring_endret_innsats: 'CHECKED',
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: 'JA',
    },
    {
        sendt: {
            value: '2024-01-29T12:28:17.393583000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-28T21:55:24.926081000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T08:26:08.463948000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: 'CHECKED',
        ny_i_arbeidslivet_dato: '2022-02-07',
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T13:06:54.479016000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T14:35:00.886581000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:54:44.524169000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T11:00:43.659327000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T10:50:16.352601000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T10:50:03.007297000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-26T18:35:54.925169000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T10:53:13.444230000Z',
        },
        drift_virksomheten_ja: null,
        drift_virksomheten_nei: 'CHECKED',
        drift_virksomheten_opphort_dato: '2024-01-10',
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:50:58.163945000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T06:21:47.197611000Z',
        },
        drift_virksomheten_ja: null,
        drift_virksomheten_nei: 'CHECKED',
        drift_virksomheten_opphort_dato: '2023-12-14',
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T13:05:50.369961000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-27T08:40:51.186686000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: 'CHECKED',
        varig_endring_omlegging_av_virksomhet: 'CHECKED',
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: 'NEI',
    },
    {
        sendt: {
            value: '2024-01-26T17:07:31.930822000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-26T15:21:12.760167000Z',
        },
        drift_virksomheten_ja: null,
        drift_virksomheten_nei: 'CHECKED',
        drift_virksomheten_opphort_dato: '2024-01-04',
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-28T18:27:04.713498000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: 'CHECKED',
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: 'JA',
    },
    {
        sendt: {
            value: '2024-01-29T11:04:34.101468000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T10:05:43.485241000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T09:55:13.719266000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T09:30:16.960092000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-25T19:57:29.270786000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: 'CHECKED',
        ny_i_arbeidslivet_dato: '2020-09-21',
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T09:38:51.759934000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T10:11:02.821953000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: 'CHECKED',
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: 'JA',
    },
    {
        sendt: {
            value: '2024-01-26T13:19:33.916954000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T10:39:54.009519000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: 'CHECKED',
        ny_i_arbeidslivet_dato: '2023-08-01',
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T14:20:08.638596000Z',
        },
        drift_virksomheten_ja: null,
        drift_virksomheten_nei: 'CHECKED',
        drift_virksomheten_opphort_dato: '2023-12-31',
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T11:30:19.852778000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: 'CHECKED',
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: 'JA',
    },
    {
        sendt: {
            value: '2024-01-29T13:23:49.175591000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:10:26.998586000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T11:12:59.486960000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:34:38.465657000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-26T10:56:54.526246000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: 'CHECKED',
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: 'JA',
    },
    {
        sendt: {
            value: '2024-01-29T11:30:55.140570000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: 'CHECKED',
        ny_i_arbeidslivet_dato: '2021-08-30',
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T09:11:04.523899000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T13:22:46.171249000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T09:14:42.582109000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T11:22:49.084149000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:44:14.211275000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-28T19:06:19.061688000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: 'CHECKED',
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: 'JA',
    },
    {
        sendt: {
            value: '2024-01-29T12:36:44.978810000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T09:43:25.262498000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-28T12:11:40.770893000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: 'CHECKED',
        ny_i_arbeidslivet_dato: '2023-07-17',
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T08:26:05.453409000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T09:37:41.631421000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T09:20:22.603805000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: 'CHECKED',
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: 'NEI',
    },
    {
        sendt: {
            value: '2024-01-29T13:06:18.580107000Z',
        },
        drift_virksomheten_ja: null,
        drift_virksomheten_nei: 'CHECKED',
        drift_virksomheten_opphort_dato: '2023-12-21',
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: null,
        varig_endring: null,
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T10:25:02.933983000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:02:45.525479000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T11:32:22.889476000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: 'CHECKED',
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: 'CHECKED',
        varig_endring_25_prosent: 'JA',
    },
    {
        sendt: {
            value: '2024-01-29T09:26:04.862018000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T10:39:15.877353000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-27T12:14:59.152255000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: 'CHECKED',
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: 'JA',
    },
    {
        sendt: {
            value: '2024-01-29T08:34:33.336833000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T12:27:17.767547000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: 'CHECKED',
        varig_endring_annet: null,
        varig_endring_25_prosent: 'NEI',
    },
    {
        sendt: {
            value: '2024-01-29T09:43:42.448355000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: 'CHECKED',
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: 'NEI',
    },
    {
        sendt: {
            value: '2024-01-26T09:13:34.963372000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-26T17:21:17.660513000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T14:22:05.691116000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-26T12:30:56.693419000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-26T08:31:31.843562000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-26T12:59:21.012914000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T11:38:13.204406000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'JA',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: 'CHECKED',
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: 'NEI',
    },
    {
        sendt: {
            value: '2024-01-29T11:46:00.403072000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
    {
        sendt: {
            value: '2024-01-29T11:43:06.735377000Z',
        },
        drift_virksomheten_ja: 'CHECKED',
        drift_virksomheten_nei: null,
        drift_virksomheten_opphort_dato: null,
        ny_i_arbeidslivet_ja: null,
        ny_i_arbeidslivet_dato: null,
        ny_i_arbeidslivet_nei: 'CHECKED',
        varig_endring: 'NEI',
        varig_endring_opprettelse_nedleggelse: null,
        varig_endring_endret_innsats: null,
        varig_endring_omlegging_av_virksomhet: null,
        varig_endring_endret_markedssituasjon: null,
        varig_endring_annet: null,
        varig_endring_25_prosent: null,
    },
]
